name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:

  docker-image:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-build

      - name: Install Python Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install -U pip
          uv pip install -U -e .
          uv pip list

      - name: Build Docker Image
        run: |
          docker build -t deflow:python${{ matrix.python-version }} -f .container/Dockerfile .
          docker image ls
